from __future__ import annotations

import os


_TRUE = {"1", "true", "yes", "on"}
_FALSE = {"0", "false", "no", "off"}


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name, "").strip().lower()
    if not raw:
        return bool(default)
    if raw in _TRUE:
        return True
    if raw in _FALSE:
        return False
    return bool(default)


def _env_int(
    name: str,
    default: int,
    *,
    minimum: int | None = None,
    maximum: int | None = None,
    odd: bool = False,
) -> int:
    raw = os.getenv(name, "").strip()
    try:
        value = int(raw) if raw else int(default)
    except ValueError:
        value = int(default)
    if minimum is not None:
        value = max(int(minimum), value)
    if maximum is not None:
        value = min(int(maximum), value)
    if odd and value % 2 == 0:
        candidate = value + 1
        if maximum is not None and candidate > maximum:
            candidate = value - 1
        value = max(int(minimum or 1), candidate)
    return int(value)


def _env_float(
    name: str,
    default: float,
    *,
    minimum: float | None = None,
    maximum: float | None = None,
) -> float:
    raw = os.getenv(name, "").strip()
    try:
        value = float(raw) if raw else float(default)
    except ValueError:
        value = float(default)
    if minimum is not None:
        value = max(float(minimum), value)
    if maximum is not None:
        value = min(float(maximum), value)
    return float(value)


USE_DYNAMIC_LAMA = _env_bool("MANGA_USE_DYNAMIC_LAMA", True)
INPAINT_PRELOAD_ENABLED = _env_bool("MANGA_INPAINT_PRELOAD", True)
FIXED_LAMA_CONCURRENT_INFERENCE = _env_bool(
    "MANGA_FIXED_LAMA_CONCURRENT_INFERENCE", False
)
DETECTOR_RESIDUE_VERIFY_ENABLED = _env_bool(
    "MANGA_DETECTOR_RESIDUE_VERIFY_ENABLED", False
)

PIPELINE_DEFAULT_WORKERS = _env_int(
    "MANGA_PIPELINE_DEFAULT_WORKERS", 2, minimum=1, maximum=32
)
PIPELINE_SLICE_WORKER_LIMIT = _env_int(
    "MANGA_PIPELINE_SLICE_WORKER_LIMIT", 8, minimum=1, maximum=64
)
DOWNLOAD_WORKER_LIMIT = _env_int(
    "MANGA_DOWNLOAD_WORKERS", 4, minimum=1, maximum=8
)
OCR_IMAGE_CACHE_MB = _env_int(
    "MANGA_OCR_IMAGE_CACHE_MB", 128, minimum=0, maximum=1024
)
OCR_JOB_CONCURRENCY_LIMIT = _env_int(
    "MANGA_OCR_JOB_CONCURRENCY_LIMIT", 2, minimum=1, maximum=8
)
OCR_JOB_ACTIVE_LIMIT = _env_int(
    "MANGA_OCR_JOB_ACTIVE_LIMIT", 2, minimum=1, maximum=8
)
FIXED_LAMA_RECYCLE_MEMORY_LIMIT_BYTES = _env_int(
    "MANGA_FIXED_LAMA_RECYCLE_MEMORY_LIMIT_BYTES",
    6 * 1024**3,
    minimum=256 * 1024**2,
    maximum=1024**4,
)

VISUAL_QC_JOB_CONCURRENCY_LIMIT = 4
VISUAL_QC_JOB_CONCURRENCY = _env_int(
    "MANGA_VISUAL_QC_JOB_CONCURRENCY",
    2,
    minimum=1,
    maximum=VISUAL_QC_JOB_CONCURRENCY_LIMIT,
)
VISUAL_QC_GLOBAL_BATCH_SIZE = _env_int(
    "MANGA_VISUAL_QC_GLOBAL_BATCH_SIZE", 2, minimum=1, maximum=8
)
VISUAL_QC_REGION_BATCH_SIZE = _env_int(
    "MANGA_VISUAL_QC_REGION_BATCH_SIZE", 4, minimum=1, maximum=8
)
VISUAL_QC_PAIR_BATCH_SIZE = _env_int(
    "MANGA_VISUAL_QC_PAIR_BATCH_SIZE", 2, minimum=1, maximum=8
)

TRANSLATION_CONNECT_TIMEOUT_SECONDS = _env_float(
    "MANGA_TRANSLATION_CONNECT_TIMEOUT_SECONDS", 10.0, minimum=1.0, maximum=300.0
)
TRANSLATION_READ_TIMEOUT_SECONDS = _env_float(
    "MANGA_TRANSLATION_READ_TIMEOUT_SECONDS", 120.0, minimum=1.0, maximum=1800.0
)
REMOTE_CONNECT_TIMEOUT_SECONDS = _env_float(
    "MANGA_REMOTE_CONNECT_TIMEOUT_SECONDS", 30.0, minimum=1.0, maximum=300.0
)
DOWNLOAD_JS_NAVIGATION_TIMEOUT_MS = _env_int(
    "MANGA_DOWNLOAD_JS_NAVIGATION_TIMEOUT_MS", 60000, minimum=1000, maximum=300000
)


TEXT_CONF_THRESHOLD = 0.20
BUBBLE_IOU_THRESHOLD = 0.30
DETECTOR_FINAL_NMS_IOU = 0.35
DETECTOR_STABLE_ID_IOU_MIN = 0.50
DETECTOR_INPUT_SIZE = 1024
DETECTOR_MAX_BOX_AREA_RATIO = 0.35
DETECTOR_CONFIDENCE_MAX = 0.999998
EDITORIAL_STORY_CANDIDATE_CONFIDENCE = 0.70
DETECTOR_MIN_BOX_SIDE = 4.0
DETECTOR_LETTERBOX_VALUE = 114
DETECTOR_MASK_THRESHOLD = 0.50
DETECTOR_MASK_HYSTERESIS_LOW_THRESHOLD = 0.32
DETECTOR_TEXT_MASK_DECODE_PAD = 8
DETECTOR_MASK_HYSTERESIS_MIN_CORE_PIXELS = 2
DETECTOR_RESIDUE_VERIFY_MAX_ROIS = 8
DETECTOR_RESIDUE_VERIFY_PAD = 12
DETECTOR_RESIDUE_VERIFY_MAX_SOURCE_SIDE = 1344
DETECTOR_NMS_SCORE_FLOOR = 0.05
DETECTION_CONTENT_STD_MIN = 24.0

MASK_DILATE_KERNEL_SIZE = 7
MASK_ADAPTIVE_DILATE_KERNEL_SIZE = 9
MASK_ADAPTIVE_BORDER_STD_THRESHOLD = 18.0
MASK_EXPAND = 8
MANUAL_MASK_THRESHOLD = 10
MANUAL_CONFIDENCE_SENTINEL = 1.0

SLICE_TARGET_HEIGHT = 2400
SLICE_SEARCH_WINDOW = 360
SLICE_MIN_HEIGHT = 800
SLICE_MAX_HEIGHT = 4096
SLICE_SAFE_CUT_BAND = 12
SLICE_FALLBACK_BAND = 18
SLICE_OVERLAP_CONTEXT = 768
SLICE_CONTENT_CANNY_LOW = 30
SLICE_CONTENT_CANNY_HIGH = 120
SLICE_BACKGROUND_DISTANCE = 18
SLICE_CONTENT_SCORE_WEIGHT = 2.0
SLICE_CLOSE_KERNEL_SIZE = 31
SLICE_CONTOUR_MIN_WIDTH = 15
SLICE_CONTOUR_MIN_HEIGHT = 15
SLICE_CONTOUR_PAD_Y = 40
SLICE_FALLBACK_TOLERANCE_RATIO = 0.08

INPAINT_SIZE = 512
DYNAMIC_LAMA_MAX_SINGLE_CROP_DIM = 1024
DYNAMIC_LAMA_MAX_SINGLE_CROP_PIXELS = 1024 * 1024
INPAINT_NATIVE_TILE_ENABLED = True
INPAINT_NATIVE_TILE_EDGE_DENSITY_MIN = 0.055
INPAINT_NATIVE_TILE_MASK_AREA_MIN = 256
INPAINT_CLUSTER_PADDING = 35
INPAINT_CROP_PADDING = 35
INPAINT_CLUSTER_MAX_DIM = 600
INPAINT_CLUSTER_SPLIT_COUNT = 3
INPAINT_CLUSTER_SPLIT_HEIGHT_FACTOR = 4.0
INPAINT_CLUSTER_LINE_OVERLAP_MIN = 0.5
INPAINT_CLUSTER_GROUP_HEIGHT_FACTOR = 3.0
INPAINT_CROP_LONG_ASPECT_THRESHOLD = 1.8
MANUAL_CROP_PADDING = 72
MANUAL_MIN_DILATION = 9
MANUAL_MAX_DILATION = 15
MANUAL_DILATION_SCALE = 0.025
MANUAL_FEATHER_RADIUS = 3
MANUAL_TILE_OVERLAP = 64
FIXED_LAMA_TILE_ASPECT = 2.0
SMART_FILL_CLEAN_RING_MARGIN = 6
SMART_FILL_CONTEXT_MARGIN_FACTOR = 3
SMART_FILL_RING_PIXELS_MIN = 32
SMART_FILL_CANNY_LOW = 64
SMART_FILL_CANNY_HIGH = 128
SMART_FILL_WHITE_LEVEL = 215
SMART_FILL_BLACK_LEVEL = 35
SMART_FILL_WHITE_RATIO_MIN = 0.97
SMART_FILL_BLACK_RATIO_MIN = 0.995
SMART_FILL_WHITE_STD_MAX = 8.0
SMART_FILL_BLACK_STD_MAX = 2.5
SMART_FILL_MIDTONE_STD_MAX = 5.0
SMART_FILL_FULL_STD_MAX = 12.0
SMART_FILL_EDGE_DENSITY_MAX = 0.01
SMART_FILL_BLACK_EDGE_DENSITY_MAX = 0.002
SMART_FILL_CHROMA_STD_MAX = 12.0
SMART_FILL_MIDTONE_MIN = 50.0
SMART_FILL_MIDTONE_MAX = 205.0
SMART_FILL_SURFACE_SEED_TOL = 24.0
SMART_FILL_SURFACE_RESIDUAL_MAX = 3.0
SMART_FILL_SURFACE_MIN_RANGE = 1.5
FIXED_LAMA_SESSION_MAX_RUNS = 4

MANIFEST_LOCK_TIMEOUT_SECONDS = 30.0
PAGE_LOCK_TIMEOUT_SECONDS = 60.0
STALE_TEMP_MAX_AGE_SECONDS = 3600.0
ORT_HIGH_CPU_THRESHOLD = 8
ORT_MEDIUM_CPU_THRESHOLD = 4
ORT_HIGH_CPU_THREADS = 4
ORT_MEDIUM_CPU_THREADS = 2
ORT_INTER_OP_THREADS = 1

OCR_MASK_CROP_PADDING = 12
OCR_MASK_PAGE_CONTEXT_PADDING = 20
OCR_MASK_EDGE_CONTEXT_TRIGGER = 3
OCR_BOX_CROP_PADDING = 20
OCR_REJECT_CONFIDENCE = 0.35
OCR_REVIEW_CONFIDENCE = 0.55
OCR_EN_SCRIPT_MISMATCH_RATIO = 0.50
OCR_UNEXPECTED_LATIN_RATIO = 0.85
OCR_SYMBOL_NOISE_RATIO = 0.45
OCR_PADDLE_MIN_SIDE = 32
OCR_PADDLE_MAX_UPSCALE = 4.0
OCR_CENTERED_SINGLE_LINE_ASPECT = 3.0
OCR_COMPLETENESS_MIN_COVERAGE = 0.70
OCR_COMPLETENESS_EDGE_MARGIN = 3
OCR_SELECTIVE_RETRY = True
OCR_RETRY_CONFIDENCE = 0.80
OCR_RETRY_MAX_PIXELS = 1_500_000
OCR_RETRY_UPSCALE = 1.35
OCR_CENTER_ANCHOR_DISTANCE_MAX = 0.22
OCR_CENTER_BAND_OVERLAP_MIN = 0.30
OCR_CENTER_AXIS_FACTOR = 0.55
OCR_CENTER_DISTANCE_MARGIN = 0.08
OCR_READING_HORIZONTAL_ASPECT = 1.20
OCR_READING_VERTICAL_ASPECT = 0.90
OCR_RUBY_SIZE_FACTOR = 0.72
OCR_MAIN_SIZE_FACTOR = 0.80
OCR_MAIN_SIZE_QUANTILE = 0.75
OCR_MAIN_LINE_ASPECT_MIN = 1.80
OCR_RUBY_OVERLAP_MIN = 0.25
OCR_RUBY_MIN_SIDE = 8.0
OCR_RUBY_DISTANCE_MIN_FACTOR = 0.20
OCR_HORIZONTAL_RUBY_DISTANCE_MAX_FACTOR = 1.20
OCR_VERTICAL_RUBY_DISTANCE_MAX_FACTOR = 1.35
OCR_RUBY_FILTER_MIN_KEEP_DIVISOR = 3
OCR_ROW_TOLERANCE_FACTOR = 0.65
OCR_ROW_SIZE_QUANTILE = 0.60
OCR_ROW_TOLERANCE_MIN = 8.0
OCR_COLUMN_TOLERANCE_FACTOR = 0.85
OCR_COLUMN_TOLERANCE_MIN = 10.0

MIN_FONT_SIZE = 6
RENDER_MIN_READABLE_FONT_SIZE = 12
RENDER_SAFE_CAPTION_EXPANSION = True
RENDER_SAFE_CAPTION_EXPANSION_RATIO = 0.20
MAX_FONT_SIZE = 48
FONT_CACHE_SIZE = 256
RENDER_AUTO_TEXT_DARK_BG_THRESHOLD = 135.0
RENDER_LINE_HEIGHT_FACTOR = 1.18
RENDER_DEFAULT_PADDING = 6
RENDER_PADDING_RATIO_MAX = 0.08
RENDER_AUTO_STROKE_WIDTH = 2
RENDER_STROKE_WIDTH_MAX = 12

VISUAL_QC_REGION_MARGIN = 64
VISUAL_QC_MERGE_GAP = 32
VISUAL_QC_DEEP_AREA_RATIO = 0.35
VISUAL_QC_MANUAL_COMPONENT_AREA_MIN = 9
VISUAL_QC_MANUAL_MASK_THRESHOLD = 10

DEEPSEEK_PRICING_VERSION = "2026-08"
DEEPSEEK_INPUT_CACHE_HIT_USD_PER_M = 0.0028
DEEPSEEK_INPUT_CACHE_MISS_USD_PER_M = 0.14
DEEPSEEK_OUTPUT_USD_PER_M = 0.28

TRANSLATION_MAX_TOKENS = 32768
TRANSLATION_PREFLIGHT_MIN_TOKENS = 1000
TRANSLATION_PREFLIGHT_PROMPT_OVERHEAD = 2500
TRANSLATION_PREFLIGHT_OUTPUT_MULTIPLIER = 2.0

REMOTE_CHUNK_BYTES = 64 * 1024
DOWNLOAD_RETRY_ATTEMPTS = 4
DOWNLOAD_RETRY_BACKOFF_SECONDS = 1.0
DOWNLOAD_STATIC_MIN_DECLARED_WIDTH = 240
DOWNLOAD_JS_MIN_IMAGE_WIDTH = 300
DOWNLOAD_JS_MAX_SCROLL_ROUNDS = 30
DOWNLOAD_JS_STABLE_ROUNDS = 3
DOWNLOAD_JS_SCROLL_WAIT_MS = 400
